service: default

runtime: python27
api_version: 1
threadsafe: true

CLOUD_SQL_USERNAME: postgres
CLOUD_SQL_PASSWORD: mgt660-strongfeather
CLOUD_SQL_DATABASE_NAME: eventbrite
CLOUD_SQL_CONNECTION_NAME: mgt660-strongfeather:northamerica-northeast1:mgt660-strongfeather

handlers:

- url: /public
  static_dir: public
  secure: always

- url: /public/app
  static_dir: public/app
  secure: always

- url: /public/assets
  static_dir: public/assets
  secure: always

- url: /public/components
  static_dir: public/components
  secure: always

- url: /public/components/event
  static_dir: public/components/event
  secure: always

- url: /.*
  script: main.app

libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest